hakuroukun_hardware_gazebo:
    rear_wheel  : 'rear_wheel_joint'
    front_steer : 'front_steer_joint'
    virtual_rear_wheels  : ['base_to_right_rear_wheel', 'base_to_left_rear_wheel']
    # virtual_front_wheels  : 'front_wheel_joint'

    # ackermann link mechanism
    enable_ackermann_link: true
    wheel_separation_w : 0.5
    wheel_separation_h : 0.79
