<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hakurounkun">

  <xacro:property name="robot_namespace" value="hakuroukun"/>
  <xacro:property name="wheel_radius" value="0.125"/>
  <xacro:property name="b2f_axis_distance" value="1.1"/>
  <xacro:property name="b_axis_length" value="0.8"/>

  <!--  -->
  <xacro:include filename="hakuroukun_inertial_macro.xacro"/>

  <!-- Gazebo plugins -->
  <gazebo>
    <!-- Load ros_control plugin -->
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>${robot_namespace}</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      <legacyModeNS>false</legacyModeNS>
    </plugin> 

  <!-- Load gazebo_ros plugin. Publish passive (non-actuated) joints from Gazebo -->
    <plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
        <robotNamespace>${robot_namespace}</robotNamespace>
        <jointName>
            front_wheel_joint
        </jointName>
        <updateRate>50</updateRate>
        <alwaysOn>true</alwaysOn>
    </plugin>
  </gazebo>

  <!-- Material -->
  <material name="grey">
    <color rgba="0 0 0 0.5"/>
  </material>

  <material name="light_grey">
    <color rgba="0.5 0.5 0.5 0.5"/>
  </material>

  <!-- Null inertial element. This is needed to make the model work with
       Gazebo. -->
  <xacro:macro name="null_inertial">
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </xacro:macro>

  <!-- Base -->
  <link name="base_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <mesh filename="package://hakuroukun_description/meshes/hakuroukun_base_link.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="grey"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <mesh filename="package://hakuroukun_description/meshes/hakuroukun_base_link.stl" scale="0.001 0.001 0.001" />
        </geometry>
    </collision>
    
    <xacro:inertial_base mass="10" x="0" y="0" z="0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_base>
  </link>

  <!-- Base foorprint-->
  <link name="base_footprint"/>
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 ${wheel_radius}"/>
  </joint>

  <!-- Left back wheel -->
  <link name="left_back_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://hakuroukun_description/meshes/hakuroukun_back_wheel.stl" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="light_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
            <mesh filename="package://hakuroukun_description/meshes/hakuroukun_back_wheel.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </collision>
    <xacro:inertial_back_wheel mass="1" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_back_wheel>
  </link>

  <joint name="left_back_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="left_back_wheel" />
    <origin xyz="0 -${b_axis_length/2} 0" rpy="0 0 3.1415" />
    <axis xyz="0 1 0"/>
  </joint>

  <transmission name="left_back_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="left_back_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </actuator>
    <joint name="left_back_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>

  <gazebo reference="left_back_wheel">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- Right back wheel -->
  <link name="right_back_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://hakuroukun_description/meshes/hakuroukun_back_wheel.stl" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="light_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://hakuroukun_description/meshes/hakuroukun_back_wheel.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </collision>

    <xacro:inertial_back_wheel mass="1" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_back_wheel>
  </link>

  <joint name="right_back_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="right_back_wheel" />
    <origin xyz="0 ${b_axis_length/2} 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
  </joint>

  <transmission name="right_back_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="right_back_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </actuator>
    <joint name="right_back_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>

  <gazebo reference="right_back_wheel">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- Front wheel -->
  <link name="front_wheel">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <mesh filename="package://hakuroukun_description/meshes/hakuroukun_front_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="light_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
            <mesh filename="package://hakuroukun_description/meshes/hakuroukun_front_wheel.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </collision>
    <xacro:inertial_front_wheel mass="1" length="0.35" radius="0.1" >
      <origin xyz="0 0 0" rpy="0 0 0" />  
    </xacro:inertial_front_wheel>
  </link>

  <joint name="front_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="front_wheel" />
    <origin xyz="${b2f_axis_distance} 0 0" rpy="0 0 1.57075"/>
    <axis xyz="0 0 1"/>
    <limit effort="30" velocity="1.0"/>
  </joint>

  <transmission name="front_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="front_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </actuator>
    <joint name="front_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>

  <gazebo reference="front_wheel">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <material>Gazebo/Grey</material>
  </gazebo>

</robot>