hakuroukun:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50  

    # Position Controllers ---------------------------------------
    front_steering_controller:
        type: position_controllers/JointPositionController
        joint: front_steer_joint

    # front_wheel_controller:
    #     type: position_controllers/JointPositionController
    #     joint: front_wheel_joint

    # Velocity Controller ---------------------------------------
    rear_left_wheel_controller:
        type: velocity_controllers/JointVelocityController
        joint: rear_left_wheel_joint
        
    rear_right_wheel_controller:
        type: velocity_controllers/JointVelocityController
        joint: rear_right_wheel_joint

        